import { WorldTheme } from './types';

export const cyberTheme: WorldTheme = {
  id: 'cyber',
  name: 'Cyberpunk Hacker',
  description:
    'Jack into the Grid and run your hacks. Every assignment is an exploit waiting to be cracked. Rep is earned, never given.',
  palette: {
    background: '#030a03',
    surface: '#0a1a0a',
    primary: '#22c55e',
    accent: '#4ade80',
    text: '#d4f7d4',
    textMuted: '#5a8a5a',
    success: '#16a34a',
    danger: '#dc2626',
  },
  vocabulary: {
    assignment: 'Hack',
    assignments: 'Hacks',
    task: 'Protocol',
    tasks: 'Protocols',
    deadline: 'Zero Day',
    deadlines: 'Zero Days',
    habit: 'Routine',
    habits: 'Routines',
    points: 'Rep',
    level: 'Clearance',
    streak: 'Uptime',
    mentor: 'Ghost',
    profile: 'Profile',
    easy: 'Basic',
    medium: 'Advanced',
    hard: 'Critical',
    boss: 'Zero Day',
    dashboardGreeting: 'Daily Ops',
    questBoard: 'Op Board',
    knowledgeCheck: 'Intel Test',
    board: 'The Grid Board',
    dailyQuote: [
      'The system rewards those who learn its rules before they break them. Study the code.',
      "Rep isn't handed out. It's extracted from hours of silent, focused work in the dark.",
      'Every elite hacker was once a script kiddie who refused to stop learning.',
      'The Grid does not care how you feel. It only cares whether your exploit runs clean.',
      'Consistency is the most dangerous hack. Run your routines; compound your clearance.',
      'A zero-day exploit missed is a lesson earned. Debrief, patch, and come back stronger.',
      'Ghost rule #1: know the target architecture cold before you touch the keyboard.',
    ],
    mentorAvatar: '👾',
    completionMessage: 'Hack Successful!',
  },
  cssTheme: 'theme-cyber',
};
