import { WorldTheme } from './types';

export const medievalTheme: WorldTheme = {
  id: 'medieval',
  name: 'Medieval RPG',
  description:
    'Embark on an academic quest through a realm of castles and chronicles. Every assignment is a quest, every deadline a boss battle.',
  palette: {
    background: '#1a1008',
    surface: '#2c1f0e',
    primary: '#c97d2a',
    accent: '#e8b84b',
    text: '#f5e6c8',
    textMuted: '#a8926a',
    success: '#4a7c4e',
    danger: '#8b2a2a',
  },
  vocabulary: {
    assignment: 'Quest',
    assignments: 'Quests',
    task: 'Sub-quest',
    tasks: 'Sub-quests',
    deadline: 'Boss Battle',
    deadlines: 'Boss Battles',
    habit: 'Daily Rite',
    habits: 'Daily Rites',
    points: 'XP',
    level: 'Level',
    streak: 'Streak',
    mentor: 'Eldrin',
    profile: 'Scholar Profile',
    easy: 'Common',
    medium: 'Rare',
    hard: 'Epic',
    boss: 'Legendary',
    dashboardGreeting: "Today's Journey",
    questBoard: 'Quest Board',
    knowledgeCheck: 'Knowledge Check',
    board: 'The Commons',
    dailyQuote: [
      'Every great scholar was once a humble apprentice. Begin your quest, one scroll at a time.',
      'The dungeon of ignorance is conquered not in a single charge, but through steady, daily discipline.',
      'Even the mightiest archmage faltered before they triumphed. Your struggle is your strength.',
      'A quest left unstarted yields no XP. Light your torch and take the first step.',
      'Wisdom is forged in the fires of effort, not found in the treasure chest of shortcuts.',
      'The guild honors those who persist when the path grows dark. Persevere, young scholar.',
      'No hero ever regretted the hours they spent sharpening their blade — or their mind.',
    ],
    mentorAvatar: '🧙',
    completionMessage: 'Quest Complete!',
  },
  cssTheme: 'theme-medieval',
};
