import { WorldTheme } from './types';

export const spaceTheme: WorldTheme = {
  id: 'space',
  name: 'Space Explorer',
  description:
    'Navigate the cosmos of knowledge aboard the Deep Space Corps. Missions await, and the universe rewards the prepared.',
  palette: {
    background: '#060d1f',
    surface: '#0d1b35',
    primary: '#0ea5e9',
    accent: '#38bdf8',
    text: '#e2f0fb',
    textMuted: '#6b9ab8',
    success: '#10b981',
    danger: '#ef4444',
  },
  vocabulary: {
    assignment: 'Mission',
    assignments: 'Missions',
    task: 'Objective',
    tasks: 'Objectives',
    deadline: 'Launch Date',
    deadlines: 'Launch Dates',
    habit: 'Training Protocol',
    habits: 'Training Protocols',
    points: 'Credits',
    level: 'Rank',
    streak: 'Chain',
    mentor: 'Commander Orion',
    profile: 'Agent File',
    easy: 'Rookie',
    medium: 'Veteran',
    hard: 'Elite',
    boss: 'Commander',
    dashboardGreeting: 'Mission Briefing',
    questBoard: 'Mission Log',
    knowledgeCheck: 'Skill Scan',
    board: 'Mission Debrief',
    dailyQuote: [
      'Space is unforgiving to the unprepared. Study hard — the cosmos rewards the ready.',
      'A great commander knows their mission inside out before the launch countdown begins.',
      'Every light-year starts with a single step off the launch pad. Begin your mission today.',
      'The stars do not wait for doubt. Execute your training protocols and chart your course.',
      "Deep Space Corps Regulation 7: A recruit who reviews yesterday's data performs better tomorrow.",
      'Failure is just a course correction. Adjust your trajectory and press on, cadet.',
      'The void between stars is vast, but discipline closes the distance one objective at a time.',
    ],
    mentorAvatar: '👨‍🚀',
    completionMessage: 'Mission Accomplished!',
  },
  cssTheme: 'theme-space',
};
